name: Deploy Azure Bicep Resources

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  actions: write
  id-token: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  DeployAzure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout self
        uses: actions/checkout@main
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        uses: Azure/bicep-deploy@v2.2.0
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          location: eastus
          action-on-unmanage-resources: detach
          deny-settings-mode: denyDelete
          resource-group-name: TESTRG1
          template-file: ./main.bicep
          parameters: '{ "storagePrefix": "mystore", "storageSKU": "Standard_LRS" }'
          
