name: Deploy Azure Bicep Resources

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  actions: write
  id-token: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  DeployAzure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout self
        uses: actions/checkout@main
      - name: Login Into Azure Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Run Azure CLI commands
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show
            az group list
      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          resourceGroupName: TESTRG1
          template: ./main.bicep
          parameters: ./mainbicepparam
          failOnStdErr: false
